In [6]:
import numpy as np #要記得先import

print(np.zeros((2,3)))
print(np.empty((2,3))) #要有兩個括號

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)


[[ 0.57822641 -1.04165524]
 [-0.90683721  0.73520027]
 [ 1.5967003  -0.74330821]]
[[0.69902276 0.09128023]
 [0.88244821 0.6439808 ]
 [0.1080252  0.32125981]]
[[3 7]
 [5 8]
 [0 0]]


In [10]:
import numpy as np

a = np.random.rand(2, 3)
a = a*100

print(a)

[[61.9791852  82.62440979 48.72312818]
 [13.32529601 99.42908215 75.29875602]]


In [11]:
print(a.round()) #利用這兩個寫法可以小數取整數
print(np.round(a))

[[62. 83. 49.]
 [13. 99. 75.]]
[[62. 83. 49.]
 [13. 99. 75.]]


In [15]:
m = 30 #讓他在m到n之間的寫法
n = 50

a = np.random.rand(2, 3)*(n-m)
b = a

print(b)
print((a-b%1)) #b除以1取餘數=小數點部分
print((a-b%1)+m)

[[ 5.85538583 16.67758871 11.91126115]
 [ 4.47070317  7.68227686 14.45018424]]
[[ 5. 16. 11.]
 [ 4.  7. 14.]]
[[35. 46. 41.]
 [34. 37. 44.]]
