In [5]:
import numpy as np

a = np.arange(11) #製作一個1到11一維陣列的寫法 #是arange not arrange!!
#怎麼製作一個1*11陣列呢???
a[(3 <= a) & (a < 8 )] *= -1

print(a)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [7]:
a = np.random.rand(2,5)
print(a)
print(a[a>0.5]) #取出陣列中，大於0.5的寫法
print(a[a>0.5].size) #要看有幾個大於0.5->用size

[[0.97803427 0.74555614 0.15931675 0.2156758  0.17366804]
 [0.82990961 0.49691177 0.40262037 0.03548851 0.34878584]]
[0.97803427 0.74555614 0.82990961]
3
