In [1]:
import numpy as np 

b = np.arange(12).reshape(3, 4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

In [2]:
print(b.sum())
# 66

print(b.sum(axis=0)) #axis=0，直的
# array([12, 15, 18, 21]) 

print(b.sum(axis=1)) #axis=1，橫的
# array([6, 22, 38])

66
[12 15 18 21]
[ 6 22 38]


In [3]:
import numpy as np 

a = np.arange(6)
# [0, 1, 2, 3, 4, 5]

print(a.reshape(3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [4]:
import numpy as np 

a = np.arange(6)
# [0, 1, 2, 3, 4, 5]

print(a.resize((3, 2)))
print(a) #reshape, resize上下兩者不同!!!!

None
[[0 1]
 [2 3]
 [4 5]]


In [8]:
import numpy as np 

a = np.arange(6).reshape((3, 2))

print(a.ravel() ) #將多維陣列轉換成一維的方法:ravel(), flatten()
print(a.flatten())
print(a.flat)
print(list(a.flat)) #要改成list才看的出來

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]


In [22]:
#2
import numpy as np

a = np.random.random((5,5)) #製作一個隨機矩陣的方法
print(a)
print(a-a.min()/ a.max()-a.min()) #正規化的意思是數據在0-1之間

[[0.3269617  0.85125732 0.70423349 0.59529217 0.19222298]
 [0.92245704 0.61064822 0.80894811 0.55144201 0.52543658]
 [0.28907459 0.9027531  0.60991777 0.14094544 0.41767267]
 [0.15227251 0.75330728 0.22696496 0.95594064 0.92238024]
 [0.01460216 0.827968   0.11127082 0.69547497 0.53902145]]
[[ 0.29708437  0.82138     0.67435616  0.56541484  0.16234565]
 [ 0.89257971  0.5807709   0.77907078  0.52156469  0.49555925]
 [ 0.25919726  0.87287577  0.58004044  0.11106811  0.38779534]
 [ 0.12239518  0.72342996  0.19708764  0.92606331  0.89250292]
 [-0.01527517  0.79809068  0.08139349  0.66559764  0.50914412]]


In [14]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#3
a = np.random.random(10)
a[a.argmax()]= -1 

print(a)
print(np.nanmax(a)) #取出最大值

[ 0.09291209  0.41473264  0.30519878  0.84254346  0.53986987 -1.
  0.17793936  0.37424424  0.36810209  0.59490935]
0.8425434570047847
