In [1]:
import numpy as np
print(np) # <module 'numpy' from '.../numpy/__init__.py'>
print(np.__version__) # 1.20.1


<module 'numpy' from 'C:\\Users\\Family\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.20.1


In [35]:
import numpy as np
a = np.random.randint(10, size=6)
b = np.random.randint(10, size=6).reshape(2,3)
c = np.random.randint(10, size=24).reshape(2,3,4)

print('list(a)',(list(a)))
print('tolist()', a.tolist())

print('list(b)',(list(b)))
print('tolist()', b.tolist())

print('list(c)',(list(c)))
print('tolist()', c.tolist())

list(a) [8, 1, 4, 5, 1, 8]
tolist() [8, 1, 4, 5, 1, 8]
list(b) [array([7, 9, 1]), array([1, 5, 5])]
tolist() [[7, 9, 1], [1, 5, 5]]
list(c) [array([[5, 7, 0, 1],
       [2, 0, 8, 2],
       [4, 0, 8, 9]]), array([[0, 3, 9, 5],
       [1, 7, 6, 4],
       [4, 2, 4, 7]])]
tolist() [[[5, 7, 0, 1], [2, 0, 8, 2], [4, 0, 8, 9]], [[0, 3, 9, 5], [1, 7, 6, 4], [4, 2, 4, 7]]]


In [25]:
print('list(a):', (list(a)))
print('tolist():',a.tolist())

list(a): [8, 8, 7, 6, 8, 9]
tolist(): [8, 8, 7, 6, 8, 9]


In [22]:
import numpy as np

a = np.random.randint(10, size=6)

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(len(a))
print(type(a))

[8 8 7 6 8 9]
1
(6,)
6
int32
6
<class 'numpy.ndarray'>


In [30]:
b = np.random.randint(10, size=(3,4))

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(len(b))
print(type(b))

[[4 3 0 1]
 [9 7 1 6]
 [3 9 4 2]]
2
(3, 4)
12
int32
3
<class 'numpy.ndarray'>


In [10]:
c = np.random.randint(10, size=(2,3,2))

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(len(c))
print(type(c))

[[[8 3]
  [8 3]
  [2 4]]

 [[3 5]
  [4 3]
  [0 2]]]
3
(2, 3, 2)
12
int32
2
<class 'numpy.ndarray'>


In [36]:
a = np.random.randint(10, size=6)
print(a.tolist())
print(list(a))

b = np.random.randint(10, size=6).reshape(2,3)
print(b.tolist())
print(list(b))

c = np.random.randint(10, size=24).reshape(2,3,4)
print(c.tolist())
print(list(c))

[1, 9, 8, 8, 9, 6]
[1, 9, 8, 8, 9, 6]
[[6, 3, 5], [3, 5, 4]]
[array([6, 3, 5]), array([3, 5, 4])]
[[[2, 0, 2, 0], [1, 4, 4, 9], [7, 6, 6, 7]], [[4, 6, 9, 7], [1, 5, 5, 7], [5, 5, 9, 0]]]
[array([[2, 0, 2, 0],
       [1, 4, 4, 9],
       [7, 6, 6, 7]]), array([[4, 6, 9, 7],
       [1, 5, 5, 7],
       [5, 5, 9, 0]])]


In [43]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))


[1, 9, 8, 8, 9, 6]
[[6, 3, 5], [3, 5, 4]]
[[[2, 0, 2, 0], [1, 4, 4, 9], [7, 6, 6, 7]], [[4, 6, 9, 7], [1, 5, 5, 7], [5, 5, 9, 0]]]
