In [2]:
#迭代攤平用法

import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in a.flat:
    print(d)

0
1
2
3
4
5


In [4]:
#正確迭代用法_迭代物件
import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a):
    print(d)
for d in np.nditer(a, order='C'): #C是橫的
    print(d)

0
1
2
3
4
5
0
1
2
3
4
5


In [3]:
import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a, order='F'): #F是直的
    print(d)

0
2
4
1
3
5


In [16]:
#hw1

import numpy as np
a = np.random.randint(0,10,1000000).reshape(100,100,100)

In [17]:
#寫法1(迴圈)
%timeit -n 10 a=2
for i in a:
    for j in i:
        for z in j:
            i = i+1

136 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
#寫法2(攤平)
%timeit -n 10 a=2
for i in a.flat:
    i = i+1

90 ns ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
#寫法3(np.nditer(a))
%timeit -n 10 a=2
for i in np.nditer(a):
    i = i+1

50 ns ± 13.1 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
#hw2

a = np.random.randint(0,10,50)
print(a)

[4 8 1 6 2 7 1 6 0 1 0 0 0 0 0 4 1 8 0 7 8 5 3 0 6 0 3 6 0 6 5 4 2 9 3 5 3
 5 7 3 1 2 3 4 3 6 2 5 4 7]


In [26]:
b = (np.bincount(a).argmax())
print(b)

0


In [27]:
np.where(a == b)[0]

array([ 8, 10, 11, 12, 13, 14, 18, 23, 25, 28], dtype=int64)

In [30]:
#hw3_做法1
a = np.random.randint(10, size=6)
print(a.tolist()) #tolist才會做巢狀的轉換
print(list(a)) #list只會做一層的轉換

b = np.random.randint(10,size=(2,3))
print(b.tolist())
print(list(b)) 

c = np.random.randint(10,size=(2, 4, 3))
print(c.tolist())
print(list(c))

[9, 6, 6, 4, 4, 3]
[9, 6, 6, 4, 4, 3]
[[1, 6, 2], [1, 0, 9]]
[array([1, 6, 2]), array([1, 0, 9])]
[[[2, 5, 8], [0, 9, 3], [3, 3, 9], [9, 5, 8]], [[0, 6, 5], [8, 6, 3], [2, 5, 5], [0, 2, 4]]]
[array([[2, 5, 8],
       [0, 9, 3],
       [3, 3, 9],
       [9, 5, 8]]), array([[0, 6, 5],
       [8, 6, 3],
       [2, 5, 5],
       [0, 2, 4]])]


In [31]:
#hw3_做法2
def tolist(iterable):
    if type(iterable) != np.array:
     return iterable
    return[tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))


[9 6 6 4 4 3]
[[1 6 2]
 [1 0 9]]
[[[2 5 8]
  [0 9 3]
  [3 3 9]
  [9 5 8]]

 [[0 6 5]
  [8 6 3]
  [2 5 5]
  [0 2 4]]]
