In [3]:
import numpy as np 
a = np.array( [20,30,40,50] )

b = np.array( [1,2,3,4] ) 

c = 1

d = np.array( [1] )

e = np.array( [1,2] ) 
print(a+a)
print(a+b)
print(a+c)
print(a+d)
print(a+e) #無法運算，因位數不同

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [7]:
A = np.ones(5)*1 #代表有五個的意思
B = np.ones(5)*2

print(A) 
print(B)
print((A+B)*(-A/2)) #因為numpy有廣播特性所以不用寫迴圈，可直接運算

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[-1.5 -1.5 -1.5 -1.5 -1.5]


In [ ]:
import numpy as np

A = np.ones(1, 6)
B = np.ones(6, 1)

print(A*B) #內積
print(A@B) #外積